# Generated by Django 5.0.1 on 2024-02-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.LWunzgdDcx2JtgDBYntqggHaFj?rs=1&pid=ImgDetMain', max_length=500),
        ),
    ]
